![image](https://raw.githubusercontent.com/IBM/watson-machine-learning-samples/master/cloud/notebooks/headers/watsonx-Prompt_Lab-Notebook.png)
# Use AutoAI RAG with predefined Milvus index to create a pattern about IBM

#### Disclaimers

- Use only Projects and Spaces that are available in watsonx context.


## Notebook content

This notebook contains the steps and code to demonstrate the usage of IBM AutoAI RAG with predefined vector store collection. Although this example uses Milvus, Elasticsearch and Chroma databases can be used similarly. Note that the AutoAI RAG experiment conducted in this notebook uses data scraped from the `ibm-watsonx-ai` SDK documentation.

Some familiarity with Python is helpful. This notebook uses Python 3.12.


## Learning goal

The learning goals of this notebook are:

- Create an AutoAI RAG job that will find the best RAG pattern based on collection created from `ibm-watsonx-ai` SDK documentation.


## Contents

This notebook contains the following parts:

1. [Set up the environment](#Set-up-the-environment)
2. [Index creation](#Index-creation)
3. [RAG Optimizer definition](#RAG-Optimizer-definition)
4. [RAG Experiment run](#RAG-Experiment-run)
5. [Comparison and testing of RAG Patterns](#Comparison-and-testing-of-RAG-Patterns)
6. [Historical runs](#Historical-runs)
7. [Cleanup](#Cleanup)
8. [Summary and next steps](#Summary-and-next-steps)

<a id="Set-up-the-environment"></a>
## Set up the environment

Before you use the sample code in this notebook, you must perform the following setup tasks:

-  Create a <a href="https://cloud.ibm.com/catalog/services/watsonxai-runtime" target="_blank" rel="noopener no referrer">watsonx.ai Runtime Service</a> instance (a free plan is offered and information about how to create the instance can be found <a href="https://dataplatform.cloud.ibm.com/docs/content/wsj/getting-started/wml-plans.html?context=wx&audience=wdp" target="_blank" rel="noopener no referrer">here</a>).

### Install and import the required modules and dependencies

In [1]:
%pip install -U "ibm-watsonx-ai[rag]>=1.4.6" | tail -n 1

Successfully installed Pillow-12.3.0 SQLAlchemy-2.0.52 XlsxWriter-3.2.9 aiohappyeyeballs-2.7.1 aiohttp-3.14.3 aiosignal-1.4.0 annotated-doc-0.0.5 annotated-types-0.8.0 anyio-4.15.1 attrs-26.1.0 bcrypt-5.0.0 beautifulsoup4-4.13.5 build-1.6.0 cachetools-7.1.8 certifi-2026.7.22 charset_normalizer-3.5.1 chromadb-1.5.9 click-8.5.0 cloudpickle-3.1.2 dataclasses-json-0.6.7 distro-1.9.0 durationpy-0.11 elastic-transport-8.19.0 elasticsearch-8.19.3 et-xmlfile-2.0.0 filelock-3.32.6 flatbuffers-25.12.19 frozenlist-1.8.0 fsspec-2026.7.0 googleapis-common-protos-1.75.3 grpcio-1.83.1 h11-0.16.0 hf-xet-1.6.0 httpcore-1.0.9 httpcore2-2.12.0 httptools-0.8.0 httpx-0.28.1 httpx-sse-0.4.3 httpx2-2.12.0 huggingface-hub-1.30.0 ibm-cos-sdk-2.14.3 ibm-cos-sdk-core-2.14.3 ibm-cos-sdk-s3transfer-2.14.3 ibm-db-3.3.0 idna-3.19 importlib-resources-7.1.0 jmespath-1.0.1 joblib-1.6.0 jsonpatch-1.33 jsonpointer-3.1.1 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 kubernetes-36.0.3 langchain-0.3.30 langchain-chroma-0.2.5 langchain-community-0.3.31 langchain-core-0.3.86 langchain-db2-0.1.7 langchain-elasticsearch-0.3.2 langchain-ibm-0.3.22 langchain-milvus-0.2.1 langchain-text-splitters-0.3.11 langgraph-0.6.11 langgraph-checkpoint-3.0.1 langgraph-prebuilt-0.6.5 langgraph-sdk-0.2.15 langsmith-0.12.2 lomond-0.3.3 lxml-6.1.3 markdown-3.8.2 markdown-it-py-4.2.0 marshmallow-3.26.2 mdurl-0.1.2 mmh3-5.3.0 multidict-6.7.1 mypy-extensions-1.1.0 narwhals-2.26.0 numpy-2.5.3 oauthlib-3.3.1 onnxruntime-1.29.0 openpyxl-3.1.5 opentelemetry-api-1.44.0 opentelemetry-exporter-otlp-proto-common-1.44.0 opentelemetry-exporter-otlp-proto-grpc-1.44.0 opentelemetry-proto-1.44.0 opentelemetry-sdk-1.44.0 opentelemetry-semantic-conventions-0.65b0 orjson-3.12.0 ormsgpack-1.12.2 overrides-7.7.0 packaging-25.0 pandas-2.3.3 propcache-0.5.2 protobuf-7.36.1 pyYAML-6.0.3 pybase64-1.5.0 pydantic-2.13.5 pydantic-core-2.46.5 pydantic-settings-2.15.0 pymilvus-2.6.6 pypdf-6.18.0 pypika-0.51.1 pyproject_hooks-1.2.0 python-docx-1.2.0 python-dotenv-1.2.3 python-pptx-1.0.2 pytz-2026.3.post1 referencing-0.37.0 requests-2.34.2 requests-oauthlib-2.0.0 requests-toolbelt-1.0.0 rich-15.0.0 rpds-py-2026.6.3 scikit-learn-1.9.0 scipy-1.18.1 shellingham-1.5.4 simsimd-6.5.16 sniffio-1.3.1 soupsieve-2.9.2 tabulate-0.10.0 tenacity-9.1.4 threadpoolctl-3.6.0 tokenizers-0.23.2 tqdm-4.70.0 truststore-0.10.4 typer-0.27.2 typing-inspect-0.9.0 typing-inspection-0.4.4 tzdata-2026.3 urllib3-2.7.0 uuid-utils-0.17.1 uvicorn-0.52.4 uvloop-0.22.1 watchfiles-1.2.0 websocket-client-1.9.2 websockets-17.1 xxhash-4.0.1 yarl-1.24.5 zstandard-0.25.0

#### Define credentials

Authenticate the watsonx.ai Runtime service on IBM Cloud Pak for Data. You need to provide the **admin's** `username` and the platform `url`.

In [2]:
import os

try:
    USERNAME = os.environ["USERNAME"]
except KeyError:
    USERNAME = input("Please enter your username (hit enter): ")

try:
    URL = os.environ["URL"]
except KeyError:
    URL = input("Please enter the platform url (hit enter): ")

Use the **admin's** `api_key` to authenticate watsonx.ai Runtime services:

In [3]:
import getpass

from ibm_watsonx_ai import Credentials

credentials = Credentials(
    username=USERNAME,
    api_key=getpass.getpass("Enter your watsonx.ai API key and hit enter: "),
    url=URL,
    instance_id="openshift",
    version="5.4",
)

Alternatively you can use the **admin's** `password`:

In [4]:
import getpass

from ibm_watsonx_ai import Credentials

if "credentials" not in locals() or not credentials.api_key:
    credentials = Credentials(
        username=USERNAME,
        password=getpass.getpass("Enter your watsonx.ai password and hit enter: "),
        url=URL,
        instance_id="openshift",
        version="5.4",
    )

#### Create `APIClient` instance

In [5]:
from ibm_watsonx_ai import APIClient

client = APIClient(credentials)

### Working with spaces

First, you need to create a space for your work. If you do not have a space already created, you can use `{PLATFORM_URL}/ml-runtime/spaces?context=icp4data` to create one.

- Click **New Deployment Space**
- Create an empty space
- Select Cloud Object Storage
- Select watsonx.ai Runtime instance and press **Create**
- Go to **Manage** tab
- Copy `Space GUID` into your env file or else enter it in the window which will show up after running below cell

**Tip**: You can also use SDK to prepare the space for your work. More information can be found [here](https://github.com/IBM/watson-machine-learning-samples/blob/master/cloud/notebooks/python_sdk/instance-management/Space%20management.ipynb).

**Action**: assign space ID below

In [6]:
import os

try:
    space_id = os.environ["SPACE_ID"]
except KeyError:
    space_id = input("Please enter your space_id (hit enter): ")

Set your space as default.

In [7]:
client.set.default_space(space_id)

'SUCCESS'

<a id="Index-creation"></a>
## Index creation

### Defining a connection to knowledge base

Provide id of connection to your knowledge database or create a new one. You can add connection on watsonx platform or type your credentials after running the code below.

In [8]:
vector_store_connection_id = (
    input(
        "Provide connection asset ID in your space. Skip this, if you wish to type credentials by hand and hit enter: "
    )
    or None
)

if vector_store_connection_id is None:
    try:
        username = os.environ["MILVUS_USER"]
    except KeyError:
        username = input("Please enter your Milvus user name and hit enter: ")
    try:
        password = os.environ["MILVUS_PASSWORD"]
    except KeyError:
        password = getpass.getpass("Please enter your Milvus password and hit enter: ")
    try:
        host = os.environ["MILVUS_HOST"]
    except KeyError:
        host = input("Please enter your Milvus hostname and hit enter: ")
    try:
        port = os.environ["MILVUS_PORT"]
    except KeyError:
        port = input("Please enter your Milvus port number and hit enter: ")
    try:
        ssl = os.environ["MILVUS_SSL"]
    except:
        ssl = bool(
            input(
                "Please enter ('y'/anything) if your Milvus instance has SSL enabled. Skip if it is not: "
            )
        )

    # Create connection
    milvus_data_source_type_id = client.connections.get_datasource_type_uid_by_name(
        "milvus"
    )
    details = client.connections.create(
        {
            client.connections.ConfigurationMetaNames.NAME: "Milvus Connection - sample notebook",
            client.connections.ConfigurationMetaNames.DESCRIPTION: "Connection created by the sample notebook",
            client.connections.ConfigurationMetaNames.DATASOURCE_TYPE: milvus_data_source_type_id,
            client.connections.ConfigurationMetaNames.PROPERTIES: {
                "host": host,
                "port": port,
                "username": username,
                "password": password,
                "ssl": ssl,
            },
        }
    )

    vector_store_connection_id = client.connections.get_id(details)

Creating connections...
SUCCESS

Download example data. You can also assign your own text to `document content`.

In [9]:
import requests

url = "https://ibm.github.io/watsonx-ai-python-sdk/v1.3.42/base.html"

response = requests.get(url)
response.raise_for_status()

document_content = response.text

Chunk and upload your document to the vector store.

In [10]:
from ibm_watsonx_ai.foundation_models.embeddings import Embeddings
from ibm_watsonx_ai.foundation_models.extensions.rag.chunker import LangChainChunker
from ibm_watsonx_ai.foundation_models.extensions.rag.vector_stores import (
    MilvusVectorStore,
)
from langchain_core.documents import Document

# Defining vector store from the connection id
embedding = Embeddings(model_id="ibm/slate-125m-english-rtrvr", api_client=client)
vector_store = MilvusVectorStore(
    api_client=client,
    connection_id=vector_store_connection_id,
    collection_name="collection_notebook_sample",
    embedding_function=embedding,
    drop_old=True,
)

# Chunking document into smaller segments
document = Document(
    page_content=document_content, metadata={"document_id": "base.html"}
)
text_splitter = LangChainChunker(method="recursive", chunk_size=256, chunk_overlap=32)
chunks = text_splitter.split_documents([document])

# Uploading document to vector store
ids = vector_store.add_documents(chunks, batch_size=300)

print(ids[:5])

['8b427f0c5f8937f53cb044e8f33eef298554344625d456dea268c6ad2474f01f', '3894eb5d7dea204d68490e08a17d87b151c8a517e14d2585574d75b1fac0d365', '038e7d15480b0e0169e4642efa5a4d4abd5b976d42f459d7732cd3037e604991', '6c904049a07ffe19a594217e0acfb6bad47716e8a52c2afd5d5a30c7edd883a5', 'd745774f5ac8e2e12a071716cb284158b57291e65cdd42ead8ee6b93950f8d00']

<a id="RAG-Optimizer-definition"></a>
## RAG Optimizer definition

### Defining a connection to vector store

Define a reference to knowledge base.

In [11]:
from ibm_watsonx_ai.helpers import DataConnection
from ibm_watsonx_ai.utils.autoai.enums import KnowledgeBaseFieldRole
from ibm_watsonx_ai.utils.autoai.knowledge_base import VectorStoreKnowledgeBase

connection = DataConnection(connection_asset_id=vector_store_connection_id)
connection.set_client(client)

vector_store_knowledge_base_references = [
    VectorStoreKnowledgeBase(
        name="Embedded base.html file",
        description="This knowledge base contains samples from watsonx.ai sdk documentation.",
        connection=connection,
        settings={
            "index_name": "collection_notebook_sample",
            "fields_mapping": [
                {
                    "role": KnowledgeBaseFieldRole.DENSE_VECTOR_EMBEDDINGS,
                    "field_name": "vector",
                },
                {
                    "role": KnowledgeBaseFieldRole.DOCUMENT_NAME,
                    "field_name": "document_id",
                },
                {
                    "role": KnowledgeBaseFieldRole.TEXT,
                    "field_name": "text",
                },
                {
                    "role": KnowledgeBaseFieldRole.CHUNK_SEQUENCE_NUMBER,
                    "field_name": "sequence_number",
                },
            ],
            "embeddings": {"model_id": "ibm/slate-125m-english-rtrvr"},
        },
    )
]

### Defining a connection to test data

Upload a `json` file that will be used for benchmarking to COS and then define a connection to this file. 
Define benchmarking question about your knowledge base. Replace the questions below.

In [12]:
benchmarking_data_IBM_page_content = [
    {
        "question": "How can you set or refresh user request headers using the APIClient class?",
        "correct_answer": "client.set_headers({'Authorization': 'Bearer <token>'})",
        "correct_answer_document_ids": ["base.html"],
    },
    {
        "question": "How to initialise Credentials object with api_key",
        "correct_answer": "credentials = Credentials(url = 'https://us-south.ml.cloud.ibm.com', api_key = '***********')",
        "correct_answer_document_ids": ["base.html"],
    },
]

Upload testing data to the bucket as a `json` file.

In [13]:
import json

test_filename = "benchmarking_data_predefined_vector_store_sample.json"

if not os.path.isfile(test_filename):
    with open(test_filename, "w") as json_file:
        json.dump(benchmarking_data_IBM_page_content, json_file, indent=4)

test_asset_details = client.data_assets.create(
    name=test_filename, file_path=test_filename
)

test_asset_id = client.data_assets.get_id(test_asset_details)
test_asset_id

Creating data asset...
SUCCESS

'01a066bd-38ff-765b-983c-225df19c0a10'

Define connection information to testing data.

In [14]:
test_data_references = [DataConnection(data_asset_id=test_asset_id)]

### RAG Optimizer configuration

Provide the input information for AutoAI RAG optimizer:
- `name` - experiment name
- `description` - experiment description
- `max_number_of_rag_patterns` - maximum number of RAG patterns to create
- `optimization_metrics` - target optimization metrics

In [15]:
from ibm_watsonx_ai.experiment import AutoAI
from ibm_watsonx_ai.foundation_models.schema import (
    AutoAIRAGGenerationConfig,
    AutoAIRAGModelConfig,
)

experiment = AutoAI(
    credentials=credentials,
    space_id=space_id,
)

foundation_model = AutoAIRAGModelConfig(
    model_id="ibm/granite-4-h-small",
)

generation_config = AutoAIRAGGenerationConfig(
    foundation_models=[foundation_model],
)

rag_optimizer = experiment.rag_optimizer(
    name="AutoAI RAG - sample notebook - knowledge base",
    description="Experiment run in sample notebook",
    generation=generation_config,
    max_number_of_rag_patterns=3,
    optimization_metrics=[AutoAI.RAGMetrics.ANSWER_CORRECTNESS],
)

Configuration parameters can be retrieved via `get_params()`.

In [16]:
rag_optimizer.get_params()

{'name': 'AutoAI RAG - sample notebook - knowledge base',
 'description': 'Experiment run in sample notebook',
 'max_number_of_rag_patterns': 3,
 'optimization_metrics': ['answer_correctness']}

<a id="RAG-Experiment-run"></a>
## RAG Experiment run

Call the `run()` method to trigger the AutoAI RAG experiment. You can either use interactive mode (synchronous job) or background mode (asynchronous job) by specifying `background_mode=True`.

In [17]:
run_details = rag_optimizer.run(
    knowledge_base_references=vector_store_knowledge_base_references,
    test_data_references=test_data_references,
    background_mode=False,
)

##############################################

Running 'fe6288f7-20b5-49e6-8bf4-4779db20ccb8'

##############################################


pending...........
running.......
completed
Training of 'fe6288f7-20b5-49e6-8bf4-4779db20ccb8' finished successfully.

You can use the `get_run_status()` method to monitor AutoAI RAG jobs in background mode.

In [18]:
rag_optimizer.get_run_status()

'completed'

<a id="Comparison-and-testing-of-RAG-Patterns"></a>
## Comparison and testing of RAG Patterns

You can list the trained patterns and information on evaluation metrics in the form of a Pandas DataFrame by calling the `summary()` method. You can use the DataFrame to compare all discovered patterns and select the one you like for further testing.

In [19]:
summary = rag_optimizer.summary()
summary

              mean_answer_correctness    generation.model_id  agent.type
Pattern_Name
Pattern1                       0.7083  ibm/granite-4-h-small  sequential
Pattern2                       0.5417  ibm/granite-4-h-small  sequential
Pattern3                       0.5417  ibm/granite-4-h-small  sequential

Additionally, you can pass the `scoring` parameter to the summary method, to filter RAG patterns starting with the best.

```python
summary = rag_optimizer.summary(scoring="answer_correctness")
```

In [20]:
rag_optimizer.get_run_details()

{'entity': {'hardware_spec': {'id': 'a6c4923b-b8e4-444c-9f43-8a7ec3020110',
   'name': 'L'},
  'knowledge_base_references': [{'description': 'This knowledge base contains samples from watsonx.ai sdk documentation.',
    'name': 'Embedded base.html file',
    'reference': {'connection': {'id': '01a066b7-f6b7-728d-87cb-983bef599012'},
     'location': {},
     'type': 'connection_asset'},
    'settings': {'embeddings': {'model_id': 'ibm/slate-125m-english-rtrvr'},
     'fields_mapping': [{'field_name': 'vector',
       'role': 'dense_vector_embeddings'},
      {'field_name': 'document_id', 'role': 'document_name'},
      {'field_name': 'text', 'role': 'text'},
      {'field_name': 'sequence_number', 'role': 'chunk_sequence_number'}],
     'index_name': 'collection_notebook_sample'},
    'type': 'vector_store'}],
  'parameters': {'constraints': {'max_number_of_rag_patterns': 3},
   'optimization': {'metrics': ['answer_correctness']},
   'output_logs': True},
  'results': [{'context': {'iteration': 0,
     'max_combinations': 20,
     'rag_pattern': {'composition_steps': ['model_selection',
       'generation',
       'optimization'],
      'duration_seconds': 16,
      'location': {'evaluation_results': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/Pattern1/evaluation_results.json',
       'inference_notebook': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/Pattern1/inference_notebook.ipynb',
       'inference_service_code': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/Pattern1/inference_ai_service.gz',
       'inference_service_metadata': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/Pattern1/inference_service_metadata.json'},
      'name': 'Pattern1',
      'settings': {'agent': {'description': 'Sequential graph with multi-index retriever and reranking.',
        'framework': 'langgraph',
        'type': 'sequential'},
       'generation': {'chat_template_messages': {'system_message_text': 'You are Granite Chat, an AI language model developed by IBM. You are a cautious assistant. You carefully follow instructions. You are helpful and harmless and you follow ethical guidelines and promote positive behaviour.',
         'user_message_text': 'You are an AI language model designed to function as a specialized Retrieval Augmented Generation (RAG) assistant. When generating responses, prioritize correctness, i.e., ensure that your response is grounded in context and user query. Always make sure that your response is relevant to the question. \nAnswer Length: detailed\n{reference_documents}\nRespond exclusively in the language of the question, regardless of any other language used in the provided context. Ensure that your entire response is in the same language as the question.\n{question} \n\n'},
        'model_id': 'ibm/granite-4-h-small',
        'parameters': {'max_completion_tokens': 2048, 'temperature': 0.2},
        'word_to_token_ratio': 1.5},
       'knowledge_base_retrievals': [{'knowledge_base_name': 'Embedded base.html file',
         'retrieval': {'method': 'window',
          'number_of_chunks': 5,
          'window_size': 2}}]},
      'settings_importance': {'agent': [{'importance': 0.2,
         'parameter': 'type'}],
       'generation': [{'importance': 0.2, 'parameter': 'foundation_model'}],
       'retrieval': [{'importance': 0.2, 'parameter': 'retrieval_method'},
        {'importance': 0.2, 'parameter': 'window_size'},
        {'importance': 0.2, 'parameter': 'number_of_chunks'}]}},
     'software_spec': {}},
    'metrics': {'test_data': [{'ci_high': 0.75,
       'ci_low': 0.6667,
       'mean': 0.7083,
       'metric_name': 'answer_correctness'},
      {'ci_high': 0.0471,
       'ci_low': 0.0272,
       'mean': 0.0371,
       'metric_name': 'faithfulness'},
      {'mean': 1.0, 'metric_name': 'context_correctness'}]}},
   {'context': {'iteration': 1,
     'max_combinations': 20,
     'rag_pattern': {'composition_steps': ['model_selection',
       'generation',
       'optimization'],
      'duration_seconds': 13,
      'location': {'evaluation_results': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/Pattern2/evaluation_results.json',
       'inference_notebook': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/Pattern2/inference_notebook.ipynb',
       'inference_service_code': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/Pattern2/inference_ai_service.gz',
       'inference_service_metadata': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/Pattern2/inference_service_metadata.json'},
      'name': 'Pattern2',
      'settings': {'agent': {'description': 'Sequential graph with multi-index retriever and reranking.',
        'framework': 'langgraph',
        'type': 'sequential'},
       'generation': {'chat_template_messages': {'system_message_text': 'You are Granite Chat, an AI language model developed by IBM. You are a cautious assistant. You carefully follow instructions. You are helpful and harmless and you follow ethical guidelines and promote positive behaviour.',
         'user_message_text': 'You are an AI language model designed to function as a specialized Retrieval Augmented Generation (RAG) assistant. When generating responses, prioritize correctness, i.e., ensure that your response is grounded in context and user query. Always make sure that your response is relevant to the question. \nAnswer Length: detailed\n{reference_documents}\nRespond exclusively in the language of the question, regardless of any other language used in the provided context. Ensure that your entire response is in the same language as the question.\n{question} \n\n'},
        'model_id': 'ibm/granite-4-h-small',
        'parameters': {'max_completion_tokens': 2048, 'temperature': 0.2},
        'word_to_token_ratio': 1.5},
       'knowledge_base_retrievals': [{'knowledge_base_name': 'Embedded base.html file',
         'retrieval': {'method': 'window',
          'number_of_chunks': 5,
          'window_size': 4}}]},
      'settings_importance': {'agent': [{'importance': 0.0,
         'parameter': 'type'}],
       'generation': [{'importance': 0.0, 'parameter': 'foundation_model'}],
       'retrieval': [{'importance': 0.0, 'parameter': 'retrieval_method'},
        {'importance': 1.0, 'parameter': 'window_size'},
        {'importance': 0.0, 'parameter': 'number_of_chunks'}]}},
     'software_spec': {}},
    'metrics': {'test_data': [{'ci_high': 0.75,
       'ci_low': 0.3333,
       'mean': 0.5417,
       'metric_name': 'answer_correctness'},
      {'ci_high': 0.0873,
       'ci_low': 0.0558,
       'mean': 0.0716,
       'metric_name': 'faithfulness'},
      {'mean': 1.0, 'metric_name': 'context_correctness'}]}},
   {'context': {'iteration': 2,
     'max_combinations': 20,
     'rag_pattern': {'composition_steps': ['model_selection',
       'generation',
       'optimization'],
      'duration_seconds': 13,
      'location': {'evaluation_results': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/Pattern3/evaluation_results.json',
       'inference_notebook': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/Pattern3/inference_notebook.ipynb',
       'inference_service_code': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/Pattern3/inference_ai_service.gz',
       'inference_service_metadata': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/Pattern3/inference_service_metadata.json'},
      'name': 'Pattern3',
      'settings': {'agent': {'description': 'Sequential graph with multi-index retriever and reranking.',
        'framework': 'langgraph',
        'type': 'sequential'},
       'generation': {'chat_template_messages': {'system_message_text': 'You are Granite Chat, an AI language model developed by IBM. You are a cautious assistant. You carefully follow instructions. You are helpful and harmless and you follow ethical guidelines and promote positive behaviour.',
         'user_message_text': 'You are an AI language model designed to function as a specialized Retrieval Augmented Generation (RAG) assistant. When generating responses, prioritize correctness, i.e., ensure that your response is grounded in context and user query. Always make sure that your response is relevant to the question. \nAnswer Length: detailed\n{reference_documents}\nRespond exclusively in the language of the question, regardless of any other language used in the provided context. Ensure that your entire response is in the same language as the question.\n{question} \n\n'},
        'model_id': 'ibm/granite-4-h-small',
        'parameters': {'max_completion_tokens': 2048, 'temperature': 0.2},
        'word_to_token_ratio': 1.5},
       'knowledge_base_retrievals': [{'knowledge_base_name': 'Embedded base.html file',
         'retrieval': {'method': 'window',
          'number_of_chunks': 3,
          'window_size': 4}}]},
      'settings_importance': {'agent': [{'importance': 0.0,
         'parameter': 'type'}],
       'generation': [{'importance': 0.0, 'parameter': 'foundation_model'}],
       'retrieval': [{'importance': 0.0, 'parameter': 'retrieval_method'},
        {'importance': 0.8208955, 'parameter': 'window_size'},
        {'importance': 0.17910448, 'parameter': 'number_of_chunks'}]}},
     'software_spec': {}},
    'metrics': {'test_data': [{'ci_high': 0.75,
       'ci_low': 0.3333,
       'mean': 0.5417,
       'metric_name': 'answer_correctness'},
      {'ci_high': 0.1067,
       'ci_low': 0.0605,
       'mean': 0.0836,
       'metric_name': 'faithfulness'},
      {'mean': 1.0, 'metric_name': 'context_correctness'}]}}],
  'results_reference': {'location': {'path': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data',
    'training': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8',
    'training_status': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/training-status.json',
    'training_log': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/output.log',
    'assets_path': '/spaces/76f10ef2-947e-4e83-8a83-d07e24f1cab1/assets/auto_ml/auto_ml.319dfde3-4532-4b26-ae0e-bb96687aeea3/wml_data/fe6288f7-20b5-49e6-8bf4-4779db20ccb8/assets'},
   'type': 'fs'},
  'status': {'completed_at': '2026-09-03T10:13:41.750Z',
   'message': {'level': 'info', 'text': 'AutoAI RAG execution completed.'},
   'running_at': '2026-09-03T10:12:53.000Z',
   'state': 'completed',
   'step': 'generation'},
  'test_data_references': [{'location': {'href': '/v2/assets/01a066bd-38ff-765b-983c-225df19c0a10?space_id=76f10ef2-947e-4e83-8a83-d07e24f1cab1',
     'id': '01a066bd-38ff-765b-983c-225df19c0a10'},
    'type': 'data_asset'}],
  'timestamp': '2026-09-03T10:13:43.225Z'},
 'metadata': {'created_at': '2026-09-03T10:11:33.299Z',
  'description': 'Experiment run in sample notebook',
  'id': 'fe6288f7-20b5-49e6-8bf4-4779db20ccb8',
  'modified_at': '2026-09-03T10:13:41.939Z',
  'name': 'AutoAI RAG - sample notebook - knowledge base',
  'space_id': '76f10ef2-947e-4e83-8a83-d07e24f1cab1'}}

### Get selected pattern

Get the RAGPattern object from the RAG Optimizer experiment. By default, the RAGPattern of the best pattern is returned.

In [21]:
best_pattern_name = summary.index.values[0]
print("Best pattern is:", best_pattern_name)

best_pattern = rag_optimizer.get_pattern()

Best pattern is: Pattern1

The pattern details can be retrieved by calling the `get_pattern_details` method:

```python
rag_optimizer.get_pattern_details(pattern_name='Pattern2')
```

Query the RAGPattern locally, to test it.

In [22]:
from ibm_watsonx_ai.deployments import RuntimeContext

runtime_context = RuntimeContext(api_client=client)
inference_service_function = best_pattern.inference_service(
    runtime_context, url=client.credentials.url
)[0]

In [23]:
question = "How to add Task Credentials?"

context = RuntimeContext(
    api_client=client,
    request_payload_json={"messages": [{"role": "user", "content": question}]},
)

inference_service_function(context)

{'body': {'choices': [{'index': 0,
    'message': {'role': 'system',
     'content': 'To add Task Credentials using the IBM watsonx.ai Python SDK, you can follow these steps:\n\n1. Import the necessary classes:\n```python\nfrom ibm_watsonx_ai import Credentials, APIClient\n```\n\n2. Create an instance of the `Credentials` class by providing the required parameters:\n```python\ncredentials = Credentials(\n    url="<url>",\n    api_key=IAM_API_KEY\n)\n```\nReplace `<url>` with the actual URL of your IBM Cloud instance, and `IAM_API_KEY` with your IBM Cloud API key.\n\nAlternatively, you can create the `Credentials` instance using a dictionary:\n```python\ncredentials = Credentials.from_dict({\n    \'url\': "<url>",\n    \'apikey\': IAM_API_KEY\n})\n```\n\n3. Create an instance of the `APIClient` class by passing the `credentials` object:\n```python\nclient = APIClient(credentials)\n```\n\n4. (Optional) If you want to set a specific space ID for the client, you can do so by passing the `space_id` parameter:\n```python\nclient = APIClient(credentials, space_id="<space_id>")\n```\nReplace `<space_id>` with the desired space ID.\n\nHere\'s a complete example:\n```python\nfrom ibm_watsonx_ai import Credentials, APIClient\n\ncredentials = Credentials(\n    url="https://us-south.ml.cloud.ibm.com",\n    api_key="your_ibm_cloud_api_key"\n)\n\nclient = APIClient(credentials)\n```\n\nWith the `APIClient` instance, you can now make API calls to interact with IBM watsonx.ai services using the provided credentials.\n\nNote: Make sure to replace `"your_ibm_cloud_api_key"` with your actual IBM Cloud API key.\n\nBy following these steps, you can easily add Task Credentials to your Python script and start using the IBM watsonx.ai SDK to interact with the available services.'},
    'reference_documents': [{'page_content': '<ul class="simple">\n<li><p>IBM watsonx.ai for IBM Cloud</p></li>\n</ul> <div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="kn">from</span><span class="w"> </span><span class="nn">ibm_watsonx_ai</span><span class="w"> </span><span class="kn">import</span> <span class="n">Credentials</span> <span class="c1"># Example of creating the credentials using an API key:</span>\n<span class="n">credentials</span> <span class="o">=</span> <span class="n">Credentials</span><span class="p">(</span> <span class="n">url</span> <span class="o">=</span> <span class="s2">&quot;https://us-south.ml.cloud.ibm.com&quot;</span><span class="p">,</span>\n    <span class="n">api_key</span> <span class="o">=</span> <span class="n">IAM_API_KEY</span>',
      'metadata': {'sequence_number': [259, 260, 261, 262, 263],
       'document_id': 'base.html'}},
     {'page_content': '</dd>\n</dl>\n<p><strong>Example:</strong></p> <div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="kn">from</span><span class="w"> </span><span class="nn">ibm_watsonx_ai</span><span class="w"> </span><span class="kn">import</span> <span class="n">Credentials</span> <span class="n">credentials</span> <span class="o">=</span> <span class="n">Credentials</span><span class="o">.</span><span class="n">from_dict</span><span class="p">({</span> <span class="s1">&#39;url&#39;</span><span class="p">:</span> <span class="s2">&quot;&lt;url&gt;&quot;</span><span class="p">,</span>\n    <span class="s1">&#39;apikey&#39;</span><span class="p">:</span> <span class="n">IAM_API_URL</span>',
      'metadata': {'sequence_number': [292, 293, 294, 295, 296],
       'document_id': 'base.html'}},
     {'page_content': '</dd>\n<dt class="field-even">Return type<span class="colon">:</span></dt>\n<dd class="field-even"><p>dict</p>\n</dd>\n</dl>\n<p><strong>Example:</strong></p> <div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="kn">from</span><span class="w"> </span><span class="nn">ibm_watsonx_ai</span><span class="w"> </span><span class="kn">import</span> <span class="n">Credentials</span> <span class="n">credentials</span> <span class="o">=</span> <span class="n">Credentials</span><span class="o">.</span><span class="n">from_dict</span><span class="p">({</span> <span class="s1">&#39;url&#39;</span><span class="p">:</span> <span class="s2">&quot;&lt;url&gt;&quot;</span><span class="p">,</span>\n    <span class="s1">&#39;apikey&#39;</span><span class="p">:</span> <span class="n">IAM_API_KEY</span>',
      'metadata': {'sequence_number': [302, 303, 304, 305, 306],
       'document_id': 'base.html'}},
     {'page_content': '<li><a class="reference internal" href="#client.APIClient.set_token"><code class="docutils literal notranslate"><span class="pre">APIClient.set_token()</span></code></a></li>\n</ul>\n</li>\n</ul>\n</li>\n<li><a class="reference internal" href="#credentials">Credentials</a><ul> <li><a class="reference internal" href="#credentials.Credentials"><code class="docutils literal notranslate"><span class="pre">Credentials</span></code></a><ul> <li><a class="reference internal" href="#credentials.Credentials.from_dict"><code class="docutils literal notranslate"><span class="pre">Credentials.from_dict()</span></code></a></li> <li><a class="reference internal" href="#credentials.Credentials.to_dict"><code class="docutils literal notranslate"><span class="pre">Credentials.to_dict()</span></code></a></li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>',
      'metadata': {'sequence_number': [322, 323, 324, 325, 326],
       'document_id': 'base.html'}},
     {'page_content': '<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="kn">from</span><span class="w"> </span><span class="nn">ibm_watsonx_ai</span><span class="w"> </span><span class="kn">import</span> <span class="n">APIClient</span><span class="p">,</span> <span class="n">Credentials</span> <span class="n">credentials</span> <span class="o">=</span> <span class="n">Credentials</span><span class="p">(</span>\n    <span class="n">url</span> <span class="o">=</span> <span class="s2">&quot;&lt;url&gt;&quot;</span><span class="p">,</span> <span class="n">api_key</span> <span class="o">=</span> <span class="n">IAM_API_KEY</span>\n<span class="p">)</span> <span class="n">client</span> <span class="o">=</span> <span class="n">APIClient</span><span class="p">(</span><span class="n">credentials</span><span class="p">,</span> <span class="n">space_id</span><span class="o">=</span><span',
      'metadata': {'sequence_number': [157, 158, 159, 160, 161],
       'document_id': 'base.html'}}]}]}}

### Deploy RAGPattern

Deployment is done by storing the defined RAG function and then by creating a deployed asset.

In [24]:
deployment_details = best_pattern.inference_service.deploy(
    name="AutoAI RAG deployment - ibm_watsonx_ai documentation",
    space_id=space_id,
    deploy_params={"tags": ["wx-autoai-rag"]},
)

######################################################################################

Synchronous deployment creation for id: '01a066c4-7928-72db-8de9-2185bbcfb21a' started

######################################################################################


initializing
Note: online_url is deprecated and will be removed in a future release. Use serving_urls instead.
......
ready


-----------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_id='01a066c4-9bc7-754f-92ce-9d7706985c5e'
-----------------------------------------------------------------------------------------------

### Test the deployed function

RAG service is now deployed in our space. To test our solution we can run the cell below. Questions have to be provided in the payload. Their format is provided below.

In [25]:
deployment_id = client.deployments.get_id(deployment_details)

payload = {"messages": [{"role": "user", "content": question}]}
score_response = client.deployments.run_ai_service(deployment_id, payload)

In [26]:
print(score_response["choices"][0]["message"]["content"])

To add Task Credentials for IBM watsonx.ai using the Python SDK, you can follow these steps:

1. Import the necessary modules:
   ```python
   from ibm_watsonx_ai import Credentials
   ```

2. Create an instance of the `Credentials` class by providing the required parameters:
   - `url`: The URL of the IBM watsonx.ai service endpoint.
   - `api_key`: Your IBM Cloud API key.

   Example:
   ```python
   credentials = Credentials(
       url="https://us-south.ml.cloud.ibm.com",
       api_key="YOUR_API_KEY"
   )
   ```

   Alternatively, you can create the `Credentials` object using a dictionary:
   ```python
   credentials = Credentials.from_dict({
       'url': "https://us-south.ml.cloud.ibm.com",
       'apikey': "YOUR_API_KEY"
   })
   ```

3. Use the `credentials` object when creating an instance of the `APIClient`:
   ```python
   from ibm_watsonx_ai import APIClient

   client = APIClient(credentials, space_id="YOUR_SPACE_ID")
   ```

   Replace `"YOUR_SPACE_ID"` with the actual space ID you want to use.

4. You can also set the token for the `APIClient` using the `set_token()` method:
   ```python
   client.set_token("YOUR_TOKEN")
   ```

   Replace `"YOUR_TOKEN"` with the actual token you want to set.

Here's a complete example that demonstrates the usage of Task Credentials:

```python
from ibm_watsonx_ai import APIClient, Credentials

# Create the credentials object
credentials = Credentials.from_dict({
    'url': "https://us-south.ml.cloud.ibm.com",
    'apikey': "YOUR_API_KEY"
})

# Create the APIClient instance with the credentials
client = APIClient(credentials, space_id="YOUR_SPACE_ID")

# Set the token for the APIClient (optional)
client.set_token("YOUR_TOKEN")

# Now you can use the client to interact with IBM watsonx.ai services
```

Make sure to replace `"YOUR_API_KEY"`, `"YOUR_SPACE_ID"`, and `"YOUR_TOKEN"` with your actual API key, space ID, and token values, respectively.

By following these steps, you can add Task Credentials to your Python code and authenticate with IBM watsonx.ai services using the provided API key or token.

<a id="Historical-runs"></a>
## Historical runs

In this section you learn to work with historical RAG Optimizer jobs (runs).

To list historical runs use the `list()` method and provide the `'rag_optimizer'` filter.

In [27]:
experiment.runs(filter="rag_optimizer").list()

,timestamp,run_id,state,auto_pipeline_optimizer name
0,2026-09-03T10:13:41.939Z,fe6288f7-20b5-49e6-8bf4-4779db20ccb8,completed,AutoAI RAG - sample notebook - knowledge base

In [28]:
run_id = run_details["metadata"]["id"]
run_id

'fe6288f7-20b5-49e6-8bf4-4779db20ccb8'

### Get executed optimizer's configuration parameters

In [29]:
experiment.runs.get_rag_params(run_id=run_id)

{'name': 'AutoAI RAG - sample notebook - knowledge base',
 'description': 'Experiment run in sample notebook',
 'max_number_of_rag_patterns': 3,
 'optimization_metrics': ['answer_correctness']}

### Get historical rag_optimizer instance and training details

In [30]:
historical_opt = experiment.runs.get_rag_optimizer(run_id)

### List trained patterns for selected optimizer

In [31]:
historical_opt.summary()

              mean_answer_correctness    generation.model_id  agent.type
Pattern_Name
Pattern1                       0.7083  ibm/granite-4-h-small  sequential
Pattern2                       0.5417  ibm/granite-4-h-small  sequential
Pattern3                       0.5417  ibm/granite-4-h-small  sequential

<a id="Cleanup"></a>
## Cleanup

To delete the current experiment, use the `cancel_run` method.

**Warning:** Be careful: once you delete an experiment, you will no longer be able to refer to it.

In [32]:
rag_optimizer.cancel_run(hard_delete=True)

'SUCCESS'

To delete the deployment, use the `delete` method. 

**Warning:** Keeping the deployment active may lead to unnecessary consumption of Compute Unit Hours (CUHs).

In [33]:
client.deployments.delete(deployment_id)

'SUCCESS'

To delete obsolete collections, us the `clear` method of `MilvusVectorStore`

In [34]:
vector_store.clear()

If you want to clean up all created assets:
- experiments
- trainings
- pipelines
- model definitions
- models
- functions
- deployments

please follow up this sample [notebook](https://github.com/IBM/watson-machine-learning-samples/blob/master/cloud/notebooks/python_sdk/instance-management/Machine%20Learning%20artifacts%20management.ipynb).

<a id="Summary-and-next-steps"></a>
## Summary and next steps

You successfully completed this notebook!

You learned how to use `ibm-watsonx-ai` to run AutoAI RAG experiments. 

Check out our _<a href="https://ibm.github.io/watsonx-ai-python-sdk/samples.html" target="_blank" rel="noopener no referrer">Online Documentation</a>_ for more samples, tutorials, documentation, how-tos, and blog posts.

### Authors and Maintainers

**Paweł Kocur**, Software Engineer at IBM watsonx.ai

**Rafał Chrzanowski**, Software Engineer at IBM watsonx.ai

Copyright © 2025-2026 IBM. This notebook and its source code are released under the terms of the MIT License.